### ISSUE TITLE
OpenGL ES support

### ISSUE THREAD

**Issue by mgood7123** [jtsiomb/libdrawtext#12]
does this library support OpenGL ES?

specifically Android GLESv3 (OpenGL ES 3.2 with EGL 1.4)

**Comment by jtsiomb** [comment]
I used it with OpenGL ES 2 on Android and iOS in the past, but now that a look at the code I realise I never backported the slight changes it needs to build the GL code correctly on android. Only the iOS parts are there. I'll try a blind merge, and if you try to use it on android, let me know if something is broken.

**Comment by jtsiomb** [comment]
Backported the android changes so I'm closing this issue. Feel free to re-open if you find something is broken.

Due to the complexity of android/iOS build systems, there's no support in the makefile for building an android library directly. You'll have to handle the build yourself, and make sure `ANDROID` is defined.
