### ISSUE TITLE
multiple dtx_prepare_range calls is failing for me.

### ISSUE THREAD

**Issue by veksha** [jtsiomb/libdrawtext#14]
Hello. When I compile unicode example (commented out cjk stuff) I get the following result:
![1](https://user-images.githubusercontent.com/275333/118899568-a8a98380-b917-11eb-8965-a72a2ef1fc94.png)
Russian characters are drawing corrupted except for the last word.

But when make only one call to dtx_prepare_range like so:
`dtx_prepare_range(fntmain, FONT_SZ, 0, 0x500);		/* cyrilic */`
(from zero to 0x500)
then russian characters are drawing as expected:
![2](https://user-images.githubusercontent.com/275333/118899814-469d4e00-b918-11eb-886e-ecb264e9719d.png)

**Comment by jtsiomb** [comment]
Thanks for letting me know. This is clearly a regression. I'll look into it.

**Comment by jtsiomb** [comment]
Issue should be fixed by the latest commit (ae67ad9). It was a regression during a code re-organization between 0.4 and 0.5, a check in the function which changes glyphmaps was omitted, which previously was forcing a flush of any buffered text drawing if the new glyphmap is different. The omission resulted in any leftover buffered text being rendered using the incorrect new glyphmap.
