### ISSUE TITLE
How to support Chinese？

### ISSUE THREAD

**Issue by SuperSkeet** [jtsiomb/libdrawtext#15]
How to support Chinese？

**Comment by jtsiomb** [comment]
See the unicode example program.

You need to open a font with chinese glyphs in it, call `dtx_prepare_range(font, font_size, range_begin, range_end);` where `range_begin` and `range_end` define the unicode code-point range to rasterize into the glyphmap texture, and then just pass utf-8 text with chinese characters in it to the text drawing functions.

Since this is not a bug report or a feature request, I'm closing the issue.
