### ISSUE TITLE
How to install Freetype to compile

### ISSUE THREAD

**Issue by BSVogler** [jtsiomb/libdrawtext#7]
Hello!

I'm having problems with the compilation process. How should I install freetype so that it is possible to compile libdrawtext? I am using visual studio 2017.

Kind regards

**Comment by jtsiomb** [comment]
First of all, this is not an issue with libdrawtext, so it doesn't belong in the issue tracker. If you wish to just ask a question (or a followup question to this) feel free to send me an email instead.

In general I avoid windows and visual studio like the plague. But I think there used to be an installer which you can find by searching for "freetype mingw" or something like that. Of course you can always also compile freetype from source if that fails. After you have freetype installed, make sure to point visual studio to the include and library directories to be able to find it.

I'm closing this since it's not an actual issue.

**Comment by BSVogler** [comment]
I will mail you then. I thought it belongs here because I expected or wished some guide in the readme. I will look at this again later this week.
